### PR TITLE
Update README.md on how to disable

### PR DESCRIPTION
**Pull request by FeeJai**
See also this issue: https://github.com/atom/whitespace/issues/49

### CODE REVIEW

**Comment by mjrk** [comment]
+1
would be soooooo cool if you could merge this so I don't have to search for it long

**Comment by thedaniel** [comment]
Thanks for this! Please post the example in the readme itself rather than linking to an issue comment.

**Comment by mjrk** [comment]
Here an alternate pull request with an example #78

**Comment by izuzak** [comment]
Closing this since https://github.com/atom/whitespace/pull/78 was merged. :bus:

**Pull request closed without merging**
