### PR TITLE
Add descriptions for config settings

### PR DESCRIPTION
**Pull request by izuzak**
As a followup on https://github.com/atom/atom/pull/9096, this adds descriptions for config settings in this package.

/cc @atom/feedback for :abc: :eyes:

### CODE REVIEW

**Comment by lee-dohm** [comment]
I'd take out the syntax-scoped note from each description. It distracts from the description of the actual setting. Is there a way that we could put a note about the syntax-scoped stuff in the description of the package itself?

**Comment by izuzak** [comment]
> I'd take out the syntax-scoped note from each description. It distracts from the description of the actual setting. Is there a way that we could put a note about the syntax-scoped stuff in the description of the package itself?

Thanks for pointing that out -- I thought about that as well, but couldn't think of a nice approach. That's rendered in Settings View, so the change would need to happen there I think, and we'd need to special-case each package which supports scoped settings. Also, note that not all of those config settings are scoped, only some, so we'd need to list the ones that are.

I think that my preferred approach would be to have a "scoped" flag for config settings (in their definition), so that we can add some small UI element next to each setting in Settings View, and then add a general note at the top to explain that. Currently, we could fake that by adding `(scoped)` or some similar text at the start of descriptions for config settings which are scoped (across all packages), but I'm not super happy with that -- it's easy to miss and sounds messy since we'd be doing detection based on string prefixes (because we wouldn't want to show the note at the top for packages which don't have scoped settings).

As things are now, I like having that text here. While it is more text than before, I don't think it's distracting personally. Perhaps some UI to show/hide the descriptions would be helpful (as a config setting for Settings View)?

Happy to hear more thoughts from you and others on :point_up:.

**Comment by lee-dohm** [comment]
Since the descriptions support Markdown now, we could at least have the scoped-setting text as a separate paragraph? Also, perhaps the link could be textualized, something like:

> To disable/enable for a certain language package, you can use syntax-scoped properties in your `config.cson`. See [the whitespace package README](https://github.com/atom/whitespace#readme) for more information.

**Comment by izuzak** [comment]
:sparkles: ideas, @lee-dohm! I just pushed an update. Here's how it looks now (much shorter):

screen shot 2015-10-17 at 11 05 36

I tried putting the scoped-properties note in a new paragraph, but that looked less readable than I expected:

screen shot 2015-10-17 at 11 04 16

One other thing we could do is completely ditch the `See [the README](https://github.com/atom/whitespace#readme) for more information.` part and use a part of the previous sentence to link to the readme. What do you think?

**Comment by lee-dohm** [comment]
> use a part of the previous sentence to link to the readme.

That's a :sparkles: idea, perhaps linking the "syntax-scoped properties" part as the link would be best?

I also agree that the paragraph idea didn't turn out as well as I had conceived :laughing:

**Comment by izuzak** [comment]
> That's a :sparkles: idea, perhaps linking the "syntax-scoped properties" part as the link would be best?

:+1: :+1: Now all descriptions fit in two lines. :heart_eyes_cat: 

screen shot 2015-10-18 at 10 00 34

**Comment by lee-dohm** [comment]
:boom: :ship:

**Pull request merged**
