### PR TITLE
Added a new removeTrailingNewlines option

### PR DESCRIPTION
**Pull request by josh18**
Added a new removeTrailingNewlines option split from the existing ensureSingleTrailingNewline option. By separating the two options we allow users to have more control.

I'm not very familiar with pull requests or Atom packages so please guide me if there is something you would like me to improve.

### CODE REVIEW

**Comment by lee-dohm** [comment]
Sorry it took a while to get back to you on this. It sounds like you're trying to solve the same problem as in https://github.com/atom/whitespace/pull/94. Is that correct?

**Comment by josh18** [comment]
No worries. Just had a look at that issue and I'm a little confused by it so I will instead explain the options I intended to create:

1. Strip extra lines from the end of the file and ensure there is a trailing new line (default, and currently how it works)
`removeTrailingNewlines = true`
`ensureSingleTrailingNewline = true`

2. Strip extra lines from the end of the file. Doesn't enforce a trailing new line.
`removeTrailingNewlines = true`
`ensureSingleTrailingNewline = false`

3. Ensure there is a trailing new line. Doesn't remove extra lines.
`removeTrailingNewlines = false`
`ensureSingleTrailingNewline = true`

Does that make sense? Most of the time users would want 1 but I have at times wished for 2/3  so I figured no harm in adding an option to let users have more choice.

**Comment by lee-dohm** [comment]
Ah ok, I misread the name of the setting. I was mistaking end of file behavior for end of line behavior. I think rather than having two separate settings with four different (and potentially confusing) combinations, I think it would be best to have one setting with four well-named possible values.

**Comment by josh18** [comment]
Hmm good point. I'm not really sure what to call the setting/values though without having really long names. Best guess at the moment:
```
trailingNewLine
- off
- enforceSingleLine
- andNewLine
- removeExtraNewLines
```
Are you thinking of an input field or a select dropdown?

**Comment by lee-dohm** [comment]
A select dropdown is what I'm thinking of.

**Comment by josh18** [comment]
Closing as never got around to finishing this and I decided that it is not something that i need.

**Pull request closed without merging**
